"use client";

import { useRouter } from "next/navigation";

export default function HowItWorksPage() {
  const router = useRouter();

  const features = [
    {
      title: "Architecture Overview",
      description: "A plain-English synthesis of the repository's core layers, technology stack, and overarching architectural design. It removes the guesswork and establishes immediate high-level comprehension.",
      icon: "widgets",
    },
    {
      title: "Visual Workflow",
      description: "An auto-generated Mermaid diagram tracing execution and data flows across the system. It maps client-side interactions to backend services so developers can visualize runtime processes.",
      icon: "account_tree",
    },
    {
      title: "Interactive Dependency Graph",
      description: "A dynamic visualization of internal module imports. Click individual file nodes to immediately isolate and trace direct dependencies and reverse dependants across the project tree.",
      icon: "hub",
    },
    {
      title: "Directory Breakdown",
      description: "Contextual documentation for critical folders. Instead of generic descriptions, it summarizes the specific role each directory plays in the system and marks files that require immediate reading.",
      icon: "folder_open",
    },
    {
      title: "Core Modules",
      description: "Logical groupings of related code files categorized by functional responsibility (e.g., Database, Authentication, Routing). Helps contributors trace cross-file concerns.",
      icon: "grid_view",
    },
    {
      title: "Starter Tasks",
      description: "Curated onboarding tickets categorized by difficulty (beginner, intermediate, advanced). Each task maps exactly which files need modifications, giving engineers immediate, practical coding goals.",
      icon: "task_alt",
    },
    {
      title: "Code Change Blueprints",
      description: "Generated by clicking \"Generate Blueprint\" on a starter task. It leverages our multi-provider fallback AI to generate a complete mock pull request, displaying original vs proposed code, inline logical rationale, and an interactive verification checklist. Developers see precisely how to build and verify their first contribution.",
      icon: "code_blocks",
    },
  ];

  return (
    <div className="bg-surface-container-lowest text-on-surface font-body-md min-h-screen flex flex-col relative">
      {/* TopNavBar */}
      <nav className="fixed top-0 w-full flex justify-between items-center h-16 px-4 md:px-16 border-b border-surface-variant bg-surface-container-lowest z-50">
        <div className="flex items-center cursor-pointer" onClick={() => router.push("/")}>
          <img
            alt="OnboardPilot Logo"
            className="h-10 w-auto object-contain select-none"
            src="/logo.png"
          />
        </div>

        <button
          onClick={() => router.push("/")}
          className="text-on-surface hover:text-[#DEC29A] transition-colors text-xs font-bold cursor-pointer uppercase tracking-wider flex items-center gap-1.5"
        >
          <span className="material-symbols-outlined text-[16px]">home</span>
          Home
        </button>
      </nav>

      {/* Main Content Area */}
      <main className="flex-1 max-w-5xl w-full mx-auto px-6 md:px-16 pt-28 pb-20 z-10">
        <header className="mb-12 text-center max-w-2xl mx-auto">
          <span className="font-label-sm text-label-sm uppercase tracking-wider text-[#DEC29A] text-xs font-bold block mb-2">
            Documentation Playbook
          </span>
          <h1 className="font-display-lg text-3xl md:text-5xl font-light text-on-surface mb-4 tracking-tight">
            How OnboardPilot Works
          </h1>
          <p className="font-body-lg text-[#A3ABC4] text-sm md:text-base leading-relaxed">
            Discover how OnboardPilot ingests open-source repositories and leverages dynamic AI fallback pipelines to generate interactive onboarding guide spaces.
          </p>
        </header>

        {/* Pipeline Section */}
        <section className="bg-surface-white border border-border-subtle rounded-xl p-6 md:p-8 mb-16 shadow-[0_4px_20px_rgba(15,23,42,0.02)]">
          <h2 className="text-xl font-bold text-on-surface mb-6 flex items-center gap-2 select-none">
            <span className="material-symbols-outlined text-primary text-[24px]">sync_alt</span>
            The Analysis Ingestion Pipeline
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 relative">
            <div className="flex flex-col">
              <div className="flex items-center gap-3 mb-3">
                <span className="w-7 h-7 rounded-full bg-[#DEC29A]/20 border border-[#DEC29A]/30 flex items-center justify-center font-bold text-xs text-[#574325]">1</span>
                <h3 className="font-semibold text-sm">Target Ingestion</h3>
              </div>
              <p className="text-text-muted text-xs leading-relaxed">
                When you paste a public GitHub repository or pull request URL, the server connects via the GitHub REST API to scan the codebase structure and identify active file modules.
              </p>
            </div>

            <div className="flex flex-col">
              <div className="flex items-center gap-3 mb-3">
                <span className="w-7 h-7 rounded-full bg-[#DEC29A]/20 border border-[#DEC29A]/30 flex items-center justify-center font-bold text-xs text-[#574325]">2</span>
                <h3 className="font-semibold text-sm">Dynamic AI Fallback</h3>
              </div>
              <p className="text-text-muted text-xs leading-relaxed">
                Our server attempts to connect to OpenRouter using free-tier coding models (such as Qwen 3 Coder). If the request is delayed or encounters a billing block, it triggers a strict 15-second timeout and seamlessly fails over to OpenAI or Gemini.
              </p>
            </div>

            <div className="flex flex-col">
              <div className="flex items-center gap-3 mb-3">
                <span className="w-7 h-7 rounded-full bg-[#DEC29A]/20 border border-[#DEC29A]/30 flex items-center justify-center font-bold text-xs text-[#574325]">3</span>
                <h3 className="font-semibold text-sm">Playbook Compilation</h3>
              </div>
              <p className="text-text-muted text-xs leading-relaxed">
                The retrieved structured JSON is parsed, sanitized, and dynamically loaded into your personalized workspace, exposing architectural notes, workflows, and interactive starter challenges.
              </p>
            </div>
          </div>
        </section>

        {/* Feature Cards Grid */}
        <section className="space-y-6">
          <h2 className="text-xl font-bold text-on-surface mb-8 select-none flex items-center gap-2">
            <span className="material-symbols-outlined text-primary text-[24px]">explore</span>
            Workspace Features Explained
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {features.map((feature, idx) => (
              <div
                key={idx}
                className="bg-surface-white border border-border-subtle rounded-xl p-6 shadow-sm hover:shadow-md transition-shadow flex items-start gap-4"
              >
                <div className="w-10 h-10 rounded-lg bg-surface-container-low border border-border-subtle flex items-center justify-center text-primary shrink-0">
                  <span className="material-symbols-outlined text-[20px]">{feature.icon}</span>
                </div>
                <div className="flex-1">
                  <h3 className="font-semibold text-sm text-on-surface mb-1">{feature.title}</h3>
                  <p className="text-text-muted text-xs leading-relaxed">{feature.description}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Back Button */}
        <div className="mt-16 text-center select-none">
          <button
            onClick={() => router.push("/")}
            className="bg-[#DEC29A] text-on-primary-fixed text-label-sm font-label-sm px-6 py-3 rounded-[2px] hover:bg-[#FCDEB5] transition-colors cursor-pointer text-xs font-bold shadow-sm"
          >
            Get Started Now
          </button>
        </div>
      </main>

      {/* Footer */}
      <footer className="w-full flex justify-between items-center py-6 px-6 md:px-16 border-t border-surface-variant bg-surface-container-lowest text-on-surface-variant text-label-sm font-label-sm text-xs font-medium select-none">
        <div>© 2026 OnboardPilot. Built for engineers.</div>
        <div className="hover:text-on-surface transition-colors cursor-pointer" onClick={() => router.push("/")}>
          Return Home
        </div>
      </footer>

      {/* Background Noise Grid */}
      <div
        className="absolute inset-0 pointer-events-none opacity-[0.1] z-0"
        style={{
          backgroundImage: "radial-gradient(#A3ABC4 1px, transparent 1px)",
          backgroundSize: "24px 24px",
        }}
      ></div>
    </div>
  );
}
